name: "ChecklistValidator for PR"
description: "Checks if all items in the PR checklist are checked."
author: "Your Name"
inputs:
  github_token:
    description: "GitHub Token"
    required: true
outputs:
  result:
    description: "The result of the checklist check"
    value: ${{ steps.checklist.outputs.result }}
runs:
  using: "composite"
  steps:
    - name: Install jq
      shell: bash
      run: sudo apt-get install jq

    - name: Validate PR checklist
      shell: bash
      run: main.sh ${{ inputs.github_token }} "${{ github.event.pull_request.url }}"
