name: "ChecklistValidator for PR"
description: "Checks if all items in the PR checklist are checked."
author: "Your Name"
inputs:
  github_token:
    description: "GitHub Token"
    required: true
outputs:
  result:
    description: "The result of the checklist check"
    value: ${{ steps.checklist.outputs.result }}
runs:
  using: "composite"
  steps:
    - name: Validate PR checklist
      shell: bash
      env:
        GITHUB_TOKEN: ${{ inputs.github_token }}
        ACTION_PATH: ${{ github.action_path }}
        PR_URL: ${{ github.event.pull_request.url }}
      run: $GITHUB_ACTION_PATH/main.sh "$PR_URL"
